### PR TITLE
fix(response-formatter): remove empty objects without values

### PR DESCRIPTION
**Pull request by sommestad**
Ensures that we don’t leave objects that will get its properties removed in a toJSON().

### CODE REVIEW

**Comment by dbrockman** [comment]
Should we really be doing this 😕

**Comment by sommestad** [comment]
I thought about it for a while and couldn't think of a good reason not to. Is there ever a case where you want to have an empty object back? Previously, we had duplicate implementation of this in VIAPI to handle vehicle info entities.

**Comment by sommestad** [comment]
OK, so do you think we should filter the objects in VIAPI for example, and not as a generic thing?

**Comment by dbrockman** [comment]
Yes. We could have a reusable function and decide to use it on a per endpoint basis. I don't think we would use it very often.

**Comment by sommestad** [comment]
Handled locally in VIAPI for now (at least).

**Pull request closed without merging**
